### ISSUE TITLE
City labels not showing

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1093]
City labels don't seem to be showing up for me at the county level, did we turn this off?  Seems like one will show up in my viewport and the rest are hidden.

![image](https://user-images.githubusercontent.com/21034/38588923-83f91a3e-3ce5-11e8-838c-666d0692dc36.png)

**Comment by pjsier** [comment]
I don't think we changed anything, but I'm guessing there might have been some slight changes when we moved to Mapbox. I'm still seeing them sometimes, but it looks like this has something to do with the collision detection on labels. It shouldn't have changed with Mapbox though, since we're sourcing the labels from our custom tiles and not the basemap
