### ISSUE TITLE
Graph tooltips: Vertical overlapping

### ISSUE THREAD

**Issue by amygroshek** [EvictionLab/eviction-maps#1211]
- Is there a way to ensure they stack and don't overlap, regardless of vertical position of the chart line?
- Alternate (left / right) the tooltips from top to bottom — but this conflicts with a potential solution to another problem (see below)
- Only show the currently hovered line (so not all at once)
- Show no tooltips and let the right side readout do the work

**Comment by amygroshek** [comment]
@james-minton From what I see, this isn't a newly introduced issue. It happens on the live site anywhere the lines in the line graph overlap. 

<img width="1064" alt="Screen Shot 2019-11-19 at 9 24 00 PM" src="https://user-images.githubusercontent.com/746182/69206700-01297600-0b13-11ea-8941-e26c09d916ce.png">

> Is there a way to ensure they stack and don't overlap, regardless of vertical position of the chart line?

Sure, we can programmatically generate these, check their locations, modify their locations, and somehow dynamically maintain their graphical connection to the dot in question, but that's really freaking complicated. What's the budget and time constraints? 

> Alternate (left / right) the tooltips from top to bottom — but this conflicts with a potential solution to another problem (see below)

That might be programmatic, and not CSS. I'd have to spend a bit of time finding out. It seems like it might introduce difficult-to-predict opportunities for failure... 

> Only show the currently hovered line (so not all at once)

Because of the way this is developed, this custom overlay to display these, that's actually a pretty major change. What would make sense is reprogramming to have tooltips on the individual line dots like the bar graph uses. But that would mean we'd have to *show* those dots for each year on each line. It would change the look of the line graph quite a bit. 

> Show no tooltips and let the right side readout do the work
If we show no tooltips, we will be removing a whole component that overlays the graph. I believe it pertains only to the line graph, not the bar graph. 

Up to you. Just let me know what you want done. :)

**Comment by james-minton** [comment]
@amygroshek @Lane Am frankly kind of stumped by this.

- programmatic stacking of tooltips: don't want to commit what sounds like would necessarily be a lot of resources to this. Was hoping maybe there was a solution built into the library.

- Alternate (left / right) the tooltips from top to bottom: realizing this would only work if the overlapping lines are in sequence or an even+odd number pairing -- e.g. if, in a top-to-bottom sequence of lines, lines 1 and 3 (both odd #s) overlap, and we set the tooltips to alternate left and right, those tooltips would still be overlapping because they'd face the same direction.

- Only show the currently hovered line (so not all at once): want to clarify (in case it wasn't clear) that this meant showing all lines at once, but only the tooltip in the place where hovered. Nevertheless we'd still have the problem of tooltips overlapping when 2 points overlap ... tooltip could alternate directions? But again, we can only do this for years past 2003 (see #1210).

- Cut tooltips from line and bar charts entirely. Let the readout on the right side do the work. It becomes harder to scan this way ... but also hard to scan when (our now-very-large) tooltips obscure each other, are out of the window frame, etc. Pros: the tooltips at their current length are a bit much / overwhelming and maybe won't be missed.

- Cut just margin of error from tooltips: not totally averse, but somehow hovering and just seeing the point estimate, then having to refer to the right side for the CI, feels frustrating. I feel like, if we're giving a tooltip readout in the chart, give the user everything.

Thoughts?

**Comment by amygroshek** [comment]
I honestly think that we're riding kind of hard on this issue and perhaps not considering the ways in which the user might use the graph to drill down on a year. The user can change the date range and the degree of overlapping in the line graph will then be altered. It's only with really long date ranges that I see a lot of this overlap.

I also think that the CI makes the tooltips very large, though. We have this really nice visual presentation of CI with the shading. Maybe that's enough... especially if it's in the legend to the side. If it affects usability I think it's reasonable to limit where the CI is displayed.  

> Alternate (left / right) the tooltips from top to bottom: realizing this would only work if the overlapping lines are in sequence or an even+odd number pairing -- e.g. if, in a top-to-bottom sequence of lines, lines 1 and 3 (both odd #s) overlap, and we set the tooltips to alternate left and right, those tooltips would still be overlapping because they'd face the same direction.

I don't love this idea, mainly because I don't think it's going to look good. I haven't looked that much into the tooltip generation yet except to add the CI values, so I can't say exactly what could be changed there, or how it would look during active use moving the cursor across the graph. But my worry is that alternating directions might look disordered. Esp with the tooltips having CI in them and being so long. We will have tooltips occupying a lot of the graph when active.

> Only show the currently hovered line (so not all at once): want to clarify (in case it wasn't clear) that this meant showing all lines at once, but only the tooltip in the place where hovered. Nevertheless we'd still have the problem of tooltips overlapping when 2 points overlap ... tooltip could alternate directions? But again, we can only do this for years past 2003 (see #1210).

The problem with this, as I described above, is that "in place" for the current tooltip implementation for the line graph is not a point on a line but a year on the graph. As I described above, we would need to remove the existing tooltip component and rewrite the tooltips to appear on mouseover of the points on the lines (currently hidden). It may change the way the line graph looks a lot to display those. But it's not a bad solution. It **will** be much less likely for a user to "discover" the feature if we change it in this way, though, because the likelihood of mousing over one of the year points on a line is less.

> But again, we can only do this for years past 2003

The range of years can be changed, so we can't determine tooltip direction using year alone. It would need to be positional or of coming from the data relative to the range size as well.

**Comment by james-minton** [comment]
Ack, so are we best off by reverting to just point estimates in tooltips, and letting the right hand readout show CIs?

**Comment by amygroshek** [comment]
^ That's probably the simplest solution, given the way things are implemented at this stage. With time we could make a change, but it might be closer to 6h than a small CSS change. I prefer moving mouseover to the line points, but it's not quite a quick change.

**Comment by james-minton** [comment]
Ok, let's revert to no CI on tooltips for the upcoming client submission, and see what they think. Thanks for your thoughts here.
