### ISSUE TITLE
Card not added properly from search

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#139]
In a user testing session:

> clicked on clarke county AL, then typed Sheboygan County WI into the search bar and a tiny, blank card popped up in the map ... this card worked fine before when she was tooling around WI and clicking on things

**Comment by pjsier** [comment]
Closed by #157

**Comment by Lane** [comment]
This seems to still be happening,  I typed "Long Island" into search and selected "Long Island, ME, USA", then received this:

![image](https://user-images.githubusercontent.com/21034/32853919-1bafb68a-c9fa-11e7-9605-af3a53e1237a.png)

**Comment by pjsier** [comment]
Hmm, this looks like a combination of two things. The first one is that we still aren't actually handling what happens when it can't find a feature. In this case, the city it's looking for isn't in the census places (screenshot below, it's one of the islands without a feature on top). For this one, it looks like we could default to something at a higher level of detail like tracts if they're available, but what do you think the best way of indicating nothing was found would be?

Screenshot of cities layer
![screen shot 2017-11-15 at 12 44 51 pm](https://user-images.githubusercontent.com/8291663/32854108-2dd3ff02-ca03-11e7-932b-d55dc9800a26.png)


Screenshot of tracts layer
![screen shot 2017-11-15 at 12 46 56 pm](https://user-images.githubusercontent.com/8291663/32854120-3a342cfe-ca03-11e7-8f98-d720e7368b02.png)

**Comment by Lane** [comment]
Ah that makes sense.  I'm not sure the best way to handle it, but zooming to the area on the map, activating an appropriate layer for that zoom level, and not adding any card would make sense to me.

We'd still need to find a way to handle this for the "Add a Location" search.  Ideally we'd only show items in that search that have data we could show in cards, but not sure if we can do that with the MapZen implementation.

**Comment by pjsier** [comment]
I think that makes sense, and depending how much we want to try and find an area we could try tracts and block groups to see if anything matches. Also, would it be worthwhile to add some kind of "toast" component that's more lightweight than the dialog? Maybe something like this? https://material.angularjs.org/latest/demo/toast

That way we could still display a small message like "Data not found for area", but it'll disappear automatically after a few seconds if not manually dismissed

**Comment by Lane** [comment]
Yeah, I think a toast component would be great for that kind of messaging.

**Comment by pjsier** [comment]
Closed by #178
