### ISSUE TITLE
Cards do not transition properly when dismissing

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#312]
Dismissing the first card when there are three expanded causes the third card to drop into the first place momentarily.  This is a side effect of expanding the cards in the 1, 2, 3 order instead of the 3, 2, 1 order.

Expected behaviour is the the cards stay in the same order when the first one is dismissed, and just slide to the left.

![card-transition](https://user-images.githubusercontent.com/21034/34177923-938ee4f4-e4c2-11e7-9a6d-10aab7c5490a.gif)

**Comment by pjsier** [comment]
Based off of the changes in #309, I think this has to do with the fact that we're doing a deep copy in the data service, which is triggering a state change for the whole array. From looking into Angular animations a bit it seems like they might be more difficult to change because they're so closely associated with state. I'm wondering if it would be easier to fix this (as well as future behavior in #290) by just triggering CSS classes with animations?

**Comment by Lane** [comment]
That could potentially be the case, but I think it's more likely the margins set on the `nth-child` rules in CSS.  Will need to test that out to confirm.

**Comment by pjsier** [comment]
Ah gotcha, that makes more sense, and is also probably easier to fix
