### ISSUE TITLE
Restrict map size to visible area?

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#371]
Right now the map viewport is still about 100vh, even when a large chunk of it is obstructed. Should we restrict the map viewport to the visible portions of the map?

**Comment by Lane** [comment]
I had it adjusting previously, which was fine anytime a UI element was added, but when a UI element was removed the map would display whitespace instead of the map.  To implement the resizing, we'll need to add some extra CSS wrappers depending on which UI elements are active, and also manually trigger a map resize on MapboxGL to make it adjust to the new size.

I opted to have them overlay instead to reduce code complexity.  I'm fine with adding in the extra CSS / JS to have it only fill the visible space, but I'm wondering what the benefits might be do doing that?

**Comment by pjsier** [comment]
Ah I forgot about the error that caused. Yeah the drawbacks outweigh the benefits, closing this
