### ISSUE TITLE
Save graph as image button

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#473]
Mentioned at Princeton meeting in the context of social share, but is something we could potentially implement separately. At best I don't think it'd be a high priority, but want to make sure it's recorded

**Comment by pjsier** [comment]
This actually sounds like it could be really easy with https://github.com/nsonnad/saveSvgAsPng/tree/clean-svg-fonts, which covers PNG and SVG including inline fonts

**Comment by Lane** [comment]
Yeah, I know there are a few libs out there to do this.  I have this one starred as well: https://github.com/Hypercubed/svgsaver

**Comment by Lane** [comment]
Tested support for these two libs and I don't think either are suitable for use on the front end as it is a bit spotty.  If we were to implement this we'd probably want to do it on Lambda instead of on the front end.  I'm going to drop this in the backlog for now to implement if time permits.  Also, not sure how well used this feature would be, seeing as how people could just screenshot or grab an image from one of the exports.

**Comment by pjsier** [comment]
Closing as a won't do
