### ISSUE TITLE
Load full map with sample data

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#54]

**Comment by pjsier** [comment]
I must have messed something up with how I set up the `prototypes/map-seed-data` branch, because I tried to make a PR for this onto `feature/year-slider`, but it says there's a merge conflict.

Either way, here's what it looks like from that branch: http://eviction-lab-prototypes.s3-website.us-east-2.amazonaws.com/map-seed-data/

I updated some of the bubble styles just to make it somewhat closer to reality, but those will definitely change

**Comment by pjsier** [comment]
Closed by #58
