### ISSUE TITLE
Eviction rankings search

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#583]
Add a component into the sidebar, utilizing `location-search.component` (or `predictive-search.component`) to search for locations. In addition to predictive search behaviour, the eviction rankings search should:

  - Close the filter / search panel if on mobile / tablet
  - Activate the location in the `rankings-panel.component`
  - Switch to the location type of the selected location (rural, mid-sized, etc)
  - Scroll to the position in the list if it is in the top 100.

**Comment by pjsier** [comment]
For the last point, are we not updating the list of 100 if it's outside the top 100? I'm fine with just updating in the data panel and showing the ranking there, but the last I remembered we were updating bars to be something like 300-400. That might not be very straightforward though

**Comment by Lane** [comment]
Good question, I thought we were just doing top 100 and showing anything outside of that in the data panel only, but will need to confirm.

**Comment by pjsier** [comment]
So I'm running into a few issues with this that we'll need to sort out:

* Should the search options be limited to the current filters?
* If not, what should display for the ranking number? Asking because right now it looks like we'll have to default to the rank out of the entire list, so if you've filtered for rural areas, a suburb may show up as ranked 10,000 even though its eviction rate is higher than all of the top 100 you're currently seeing
* For list items returned as search results outside the currently filtered top 100, should we allow for using the arrow navigation to go through the rankings? I'm leaning no, since it could just get confusing, but it depends on the previous question

I've got a working demo that implements most of the functionality, but will be dependent on decisions on those questions that I'll open a PR for

**Comment by Lane** [comment]
**Should the search options be limited to the current filters?**
No, the user should be able to search for any place that exists in the rankings, even if it doesn't match the current filter.  However, if we can make the top suggestions places that meet the criteria of the current filters, that could be nice.

**If not, what should display for the ranking number?**
Could we check if the searched item exists within the current filter parameters?  If so, show the rank based on that, if not switch the region filter to "United States" and show it in the context of that?

**For list items returned as search results outside the currently filtered top 100, should we allow for using the arrow navigation to go through the rankings?**
I believe we had discussed this early on, and the answer was yes.  Will follow up to confirm.

**Comment by pjsier** [comment]
We could put the currently filtered items at the top of the search suggestions, but I’ll have to see if it has any performance issues. It should probably be fine though

So if the selected search item isn’t visible, the filters should be changed to United States and its area type so that it is in the list? That works for me

And for the arrows I think you’re right, but if we change the filters on search select it’s not an issue anyway, so that works for me

**Comment by Lane** [comment]
Re-opening, still need to add the functionality:

- Scroll to the position in the list if it is in the top 100.
- Close the filter / search panel if on mobile / tablet

**Comment by pjsier** [comment]
Ah thanks, I missed those. I can update the scroll position after #602 is merged, but I'm guessing closing the filter/search panel is dependent on some styling updates so I'll hold off there
