### ISSUE TITLE
Windows: Page width changes when opening dialogs

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#852]
Similar to #828, opening a dialog causes page width to change on Windows browsers.

**Comment by pjsier** [comment]
It looks like these are actually separate issues. This one is caused by `ngx-bootstrap` adding `padding-right` to the body if it detects an overflow, but since we're setting `overflow-x: hidden` on the `html` element, it ends up just adding extra padding. Not sure whether it's better to do a `padding-right: 0 !important` on `html`, or to try and unset the `overflow-x` property when a modal is open even though the `modal-open` class is on the body element
