### ISSUE TITLE
IE11: Crash on moving year slider

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#853]
- **Device/Browser**: Windows 10/IE 11
  - **Resolution:** 1423x800 (3200x1800 @ 225% zoom)
  - **Problem**: When moving the year slider to a year that has to load new tiles, the browser window becomes unresponsive, and prompts to "stop long running script".  Stopping the script turns all bubbles black.  The new data will eventually load, but the browser can be unresponsive for up to a minute.
  - **Expected**: The bubbles should update without locking up the browser.
  - **To Reproduce:** Load a view with a lot of bubbles, move the year slider from a post 2010 year to a pre 2010 year or vice versa.

![image](https://user-images.githubusercontent.com/21034/37673029-d5298036-2c34-11e8-89f9-7ccc341df49d.png)

Not sure there is much we can do to improve performance when switching to a year that needs a new tileset, but maybe we could show a warning if there is no way to improve performance.

**Comment by pjsier** [comment]
I've noticed this occasionally on mobile, and I'm guessing it's because changing the year fires off a bunch of events, and they probably don't terminate cleanly if you trigger it again before it finishes. Crossing between 2010/pre-2010 seems to make it a lot worse because of all the network requests and web workers it sets up. Is this specific to bubbles though? I've mostly noticed it on county layers with most of the US in the view, whether bubbles are visible or not

**Comment by Lane** [comment]
Nope, not specific to bubbles.  Happens with just choropleths active as well.
